### ISSUE TITLE
Enable ssh console access

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_init_gadget#14]
Since `nerves_firmware_ssh` is in use anyway, there's not much left to do except start the ssh daemon and point it to the same ssh key. It seems convenient especially for non-gadget port users.

**Comment by GregMefford** [comment]
This seems like a great alternative to `iex --remsh` for use in production.

**Comment by electricshaman** [comment]
Console or IEx access?

**Comment by fhunleth** [comment]
IEx

**Comment by electricshaman** [comment]
I’m not against it but the idea of having it enabled out of the gate for all users makes me a little nervous.  What if we made it super easy to switch on?  Something in the spirit of how Raspian lets you enable SSH by touching `ssh` on the boot partition?

**Comment by fhunleth** [comment]
I'd think that we'd expose a config option like the other nerves_init_gadget features. However, I don't see the security risk here. The default is no authorized keys and our `nerves_firmware_ssh` instructions are to only allow your ssh key.

**Comment by electricshaman** [comment]
I see what you’re saying and humbly disagree but I don’t feel too strongly about it.  It’s all according to one’s level of paranoia, I suppose.

Sign me up (as long as we can disable it 🤓).

**Comment by fhunleth** [comment]
Just for education's sake, do people not keep their ssh keys secure or do you not trust the ssh implementation? I'm really confused at the risk you seem to suggest is being added.

**Comment by electricshaman** [comment]
It's more of an information leakage thing for me.  I can identify a remote device based on its stock configuration.  The less we expose, the better.  But again, I don't feel that strongly about it.  

What port were you proposing to listen on?

**Comment by fhunleth** [comment]
The standard ssh port, port 22.

**Comment by electricshaman** [comment]
~That's the first place any port scanner is going to look.~

**Comment by electricshaman** [comment]
I guess if it’s on 22 then it’s less unique than picking something else (just for Nerves).  I’m OK w/ that.  Port 22 is more ubiquitous, so it reveals less about Nerves devices using `nerves_init_gadget` from a recon standpoint. 

I am in favor of port 22.

**Comment by electricshaman** [comment]
Is there any risk we would have to change away from port 22 for `IEx` if we decided someday in the future to expose the busybox console over SSH on that standard port?

**Comment by GregMefford** [comment]
I don't think there's any significant security gain to be had by using a non-standard port. Sure, you'll avoid things scanning across the entire Internet looking for open SSH ports, but:

1. You probably shouldn't have your device directly connected to the Internet anyway.
2. There are scanners out there scanning all ports anyway, so you're going to end up on Shodan either way.
3. If your concern is about behind-the-firewall threats, really the problems are the same: if someone's port-scanning, you only save yourself about 30 seconds by using a non-standard port (at the cost of the intended user needing to remember what port to use). ;)

I don't foresee us wanting to expose both Iex and Busybox shells over SSH, because you could get to one from the other, and our strategy so far with Nerves has been to prefer keeping things inside the BEAM, so IEx seems like the right default.

All that said, we should make it configurable so you can pick whatever port you need in your environment.

**Comment by electricshaman** [comment]
To be clear, I am not arguing against port 22.

**Comment by ConnorRigby** [comment]
I meant to chime in on this a while back, but i've actually done this before in a project. I also think it should be disabled by default, although i agree with @fhunleth that defaulting to no authorized keys makes it probably not that big of a deal.

**Comment by fhunleth** [comment]
Fixed in #21.
